from modules.group_coordinates import agrupar_coordenadas
from modules.find_rectangle import encontrar_retangulo
from modules.separate_lines import separar_linhas
from modules.detect_retangle import detect_retangle
